### ISSUE TITLE
[Feature 4.1] Rectangle Intersection 

### ISSUE THREAD

**Issue by jybluekim** [jybluekim/EPI#1]
Given two rectangles where each rectangle is represented as a list of 4 integers [base_x, base_y, width, height], check if there's an intersection (as in non-zero area) between the two rectangles or not.

To be more precise, write a fn that returns True if there is intersection and False if not. 

Use graphics.py to visualize results.

**Comment by alexisjkim** [comment]
I worked on it but there is a problem and the yellow intersection is in the wrong place.
